1. Add package install function 2. Tweak call_wifi_scanner_gui function 3. Add .png to QR_PNG in call_qr_gui function 4. Delete duplicate call_wifi_terminal function 5. Change small things such as indentation

diff --git a/wifi-qr b/wifi-qr
--- a/wifi-qr
+++ b/wifi-qr
@@ -66,7 +66,7 @@ main_menu() {
   elif [[ "$CHOICE" =~ "See version" ]]; then
     zenity --info --icon-name=wifi-qr --title="WiFi QR Version" --no-wrap --text=" This is wifi-qr version $VERSION"
     main_menu
- else
+  else
 	exit 0
   fi
 }
@@ -74,7 +74,9 @@ main_menu() {
 
 #GUI
 call_wifi_gui() {
-   IFS=$'\r\n' GLOBIGNORE='*' command eval  'wifilist=($(nmcli -g NAME connection))'
+  check_for_package
+  nmcli radio wifi on
+  IFS=$'\r\n' GLOBIGNORE='*' command eval  'wifilist=($(nmcli -g NAME connection))'
 
   WIFIS=$(zenity --list --column="SSID" \
 	  --width=300 --height=600 \
@@ -90,10 +92,10 @@ call_wifi_gui() {
 }
 
 call_qr_gui() {
-    call_wifi_pass
-    QR_PNG="/tmp/wifi-qr-$(echo $WIFIS | tr -dc '[:alnum:]')"
-    qrencode -l h -s 14 -o $QR_PNG "WIFI:S:$WIFIS;P:$KEEY;$PSSK$H;"
-    xdg-open $QR_PNG
+  call_wifi_pass
+  QR_PNG="/tmp/wifi-qr-$(echo $WIFIS | tr -dc '[:alnum:]').png"
+  qrencode -l h -s 14 -o $QR_PNG "WIFI:S:$WIFIS;P:$KEEY;$PSSK$H;"
+  xdg-open $QR_PNG
 }
 call_current_wifi_gui() {
 	current_wifi_ssid
@@ -102,7 +104,9 @@ call_current_wifi_gui() {
 
 #WiFi Command from terminal
 call_wifi_terminal() {
- IFS=$'\r\n' GLOBIGNORE='*' command eval  'wifilist=($(nmcli -g NAME connection))'
+  check_for_package
+  nmcli radio wifi on
+  IFS=$'\r\n' GLOBIGNORE='*' command eval  'wifilist=($(nmcli -g NAME connection))'
   OLD_IFS=$IFS
   IFS=$'\n'
   for l in ${wifilist[@]}; do
@@ -130,6 +134,7 @@ call_wifi_terminal() {
 }
 
 terminal_qr() {
+  check_for_package
   call_wifi_pass
   qrencode -o - -t UTF8 "WIFI:S:$WIFIS;P:$KEEY;$PSSK$H;"
   echo 
@@ -174,37 +179,6 @@ call_wifi_pass() {
   echo -e "${RESET}"
 }
 
-#WiFi Command from terminal
-call_wifi_terminal() {
-   IFS=$'\r\n' GLOBIGNORE='*' command eval  'wifilist=($(nmcli -g NAME connection))'
-
-  for l in "${wifilist[@]}"; do
-    array[$i]=$l
-    i=$(($i + 1))
-  done
-
-  i=0
-  for m in "${array[@]}"; do
-    echo
-    echo "$((i++))) $(basename "$m")"
-  done
-  IFS=$OLD_IFS
-
-  echo ""
-  echo -e "${BLUE}===========================================${RESET}"
-  echo -e "${BOLD}${WHITE}please choose WiFi ssidi ${RESET}"
-  echo -e "${BLUE}===========================================${RESET}"
-  read -e wifissid
-  WIFIS=${array[$wifissid]}
-  echo -e "${BLUE}===========================================${RESET}"
-  echo -e "${BOLD}${WHITE} $WIFIS"
-  echo -e "\nYou choose SSID is: $WIFIS\n ${RESET}"
-  echo -e "${BLUE}===========================================${RESET}"
-  call_wifi_pass
-  qrencode -o - -t UTF8 "WIFI:S:$WIFIS;P:$KEEY;$PSSK$H;"
-  echo
-}
-
 call_wifi_scan() {
   # Vars
   wifiqrdata=''
@@ -244,23 +218,23 @@ call_wifi_scan() {
     QHIDE=${wifiqrcred[H]}
     QTYPE=${wifiqrcred[T]}
 
-   if [[ "$QHIDE" == "true" ]]; then
-       echo -e "${GREEN}==================${RESET}"
-       echo -e "${BOLD}${WHITE}It's is HIDDEN ${RESET}"
-       echo -e "${GREEN}==================${RESET}"
+    if [[ "$QHIDE" == "true" ]]; then
+      echo -e "${GREEN}==================${RESET}"
+      echo -e "${BOLD}${WHITE}It's is HIDDEN ${RESET}"
+      echo -e "${GREEN}==================${RESET}"
 
-   elif nmcli device wifi list | grep -w "$QSSID"; then
+    elif nmcli device wifi list | grep -w "$QSSID"; then
       echo -e "${GREEN}==================${RESET}"
       echo -e "${BOLD}${WHITE}$QSSID is Online ${RESET}"
       echo -e "${GREEN}==================${RESET}"
       QSSIDO=ON
 
-   else
+    else
       echo -e "${RED}==================${RESET}"
-      echo -e "${BOLD}${WHITE}cant see $QSSID ${RESET}"
+      echo -e "${BOLD}${WHITE}Can't find $QSSID ${RESET}"
       echo -e "${RED}==================${RESET}"
       QSSIDO=OFF
-   fi 
+    fi 
  
 
   else
@@ -275,13 +249,13 @@ call_wifi_scan() {
 # key-mgmt type convert
 
   if [[ -z "$QTYPE" ]] ; then
-         NTYPE="none"
+    NTYPE="none"
   elif [[ "$QTYPE" == "WEP" ]] ; then
-         NTYPE="ieee8021x"
+    NTYPE="ieee8021x"
   elif [[ "$QTYPE" == "WPA" ]] ; then
-         NTYPE="wpa-psk"
+    NTYPE="wpa-psk"
   else
-         echo "unknow or need to add key-mgmt type"
+    echo "unknow or need to add key-mgmt type"
   fi
 
 
@@ -291,6 +265,7 @@ call_wifi_scan() {
 
 
 call_wifi_scan_terminal() {
+  check_for_package
 	call_wifi_scan
 
 	if [[ "$QHIDE" == "true" ]]; then
@@ -304,6 +279,7 @@ call_wifi_scan_terminal() {
 }
 
 call_wifi_scan_gui() {
+  check_for_package
   call_wifi_scan
   # Function with QR data
   if [[ "$QSSIDO" =~ "ON" ]]; then
@@ -314,23 +290,38 @@ call_wifi_scan_gui() {
       exit
     fi
   elif [[ "$QSSIDO" =~ "OFF" ]]; then
-    zenity --question --title="Can't find WiFi" --text="Can't find '$QSSID'.\nDo you want to retry the scan?" --width=200 --height=120 --icon-name=network-wireless-offline 2>/dev/null
-    if [ $? = 0 ]; then
+    CHOICE=$(zenity --list \
+      --title="Can't find WiFi" \
+      --text="Choose:" \
+      --radiolist \
+      --width=400 --height=180 \
+      --column="Check" --column="Option" \
+      --icon-name=network-wireless-offline \
+      TRUE "Retry scanning internally" \
+      FALSE "Retry submitting another QR Code" )
+    if [[ "$CHOICE" =~ "Retry scanning internally" ]]; then
+      echo e "${BOLD}Scanning in progess ... ${Reset}"
       nmcli radio wifi off
       sleep 5
       scan_connect
+      if [ $? != 0 ]; then
+        echo -e "${RED}==================${RESET}"
+        echo -e "${BOLD}${WHITE}Can't find $QSSID ${RESET}"
+        echo -e "${RED}==================${RESET}"
+        exit
+      fi
+    elif [[ "$CHOICE" =~ "Retry submitting another QR Code" ]]; then
+      call_wifi_scan_gui
     else
       exit
     fi
-  elif 
-    [[ "$QHIDE" =~ "true" ]]; then
+  elif [[ "$QHIDE" =~ "true" ]]; then
     zenity --question --title="Connect to Hidden WiFi" --text="Connect to '$QSSID'?" --width=200 --height=120 --icon-name=network-wireless 2>/dev/null
-       if [ $? = 0 ]; then
-      	  scan_connect_hidden
-    	else
-      	  exit
-       fi
-
+    if [ $? = 0 ]; then
+      scan_connect_hidden
+    else
+      exit
+    fi
   fi
 }
 
@@ -347,6 +338,22 @@ scan_connect_hidden() {
   nmcli con modify "$QSSID" wifi-sec.key-mgmt "$NTYPE" >/dev/null 2>&1
   nmcli con modify "$QSSID" wifi-sec.psk "$QKEES" >/dev/null 2>&1
   nmcli con up "$QSSID" >/dev/null 2>&1
+}
+
+check_for_package() {
+  PKG="qrencode zbar-tools"
+  dpkg -s $PKG 1>/dev/null 2>&1
+  while [ $? != 0 ]; do
+    read -p "Required packages for this program not found!! Do you wish to install required packages ${BOLD}$PKG${RESET} [Y/n]? " yn
+    case $yn in
+        [Yy]* ) 
+          echo -e "${BOLD}${RED}Installation requires sudo privileges!! ... ${RESET}"
+          sleep 2
+          sudo apt install -y $PKG; break;;
+        [Nn]* ) exit;;
+        * ) echo "Please answer yes or no.";;
+    esac
+  done
 }
 
 case $1 in
