current ssid to help menu

diff --git a/wifi-qr b/wifi-qr
--- a/wifi-qr
+++ b/wifi-qr
@@ -33,7 +33,7 @@ VERSION=0.1.1
 #RAW DATA SAMPLE
 #"WIFI:S:$SSID;P:$PASSWORD;T:$KEY_TYPE;H:$true;"
 #qrencode -o - -t UTF8 
-#qrencode -l h -s 14 -o /tmp/$QR 
+#qrencode -l h -s 14 -o 
 
 #GUI Mainmenu
 main_menu() {
@@ -73,7 +73,10 @@ else
 call_wifi_gui() {
 	IFS=$'\r\n' GLOBIGNORE='*' command eval  'wifilist=($(nmcli -g NAME connection))'
 
-  WIFIS=$(zenity --list --column="SSID" --width=300 --height=600 "${wifilist[@]}")
+  WIFIS=$(zenity --list --column="SSID" \
+	  --width=300 --height=600 \
+	  --title="Select SSID" \
+	  "${wifilist[@]}")
 
   if [ -z "$WIFIS" ]; then
     zenity --error --text="No WiFi network selected!" --width=200 --title="WiFi and QR Code"
@@ -88,7 +91,6 @@ call_wifi_gui() {
 
 #WiFi Command from terminal
 call_wifi_terminal() {
-#  cd "$WIFIDIR"
  IFS=$'\r\n' GLOBIGNORE='*' command eval  'wifilist=($(nmcli -g NAME connection))'
   OLD_IFS=$IFS
   IFS=$'\n'
@@ -106,18 +108,33 @@ call_wifi_terminal() {
 
   echo ""
   echo -e "${BLUE}===========================================${RESET}"
-  echo -e "${BOLD}${WHITE}please choose WiFi ssid{RESET}"
+  echo -e "${BOLD}${WHITE}please choose WiFi ssid ${RESET}"
   echo -e "${BLUE}===========================================${RESET}"
   read -e wifissid
   WIFIS=${array[$wifissid]}
   echo -e "${BLUE}===========================================${RESET}"
-  echo -e "${BOLD}${WHITE} $WIFIS"
   echo -e "\nYou choose SSID is: $WIFIS\n ${RESET}"
   echo -e "${BLUE}===========================================${RESET}"
+  terminal_qr
+}
+
+terminal_qr() {
   call_wifi_pass
   qrencode -o - -t UTF8 "WIFI:S:$WIFIS;P:$KEEY;$PSSK$H;"
-  echo
+  echo 
 }
+
+current_wifi_qr() {
+  WIFIS="$(nmcli -t -f active,ssid dev wifi | egrep '^yes' | cut -d\: -f2)"
+
+  echo -e "${BLUE}===========================================${RESET}"
+  echo -e "\nYou current active SSID is:${BOLD}${RED} $WIFIS\n ${RESET}"
+  echo -e "${BLUE}===========================================${RESET}"
+
+  terminal_qr
+}
+
+#Data Extractor nmcli version
 call_wifi_pass() {
   SSID="$WIFIS"
   KEEY=$(nmcli -g 802-11-wireless-security.psk  -s connection show "$WIFIS")
@@ -148,6 +165,7 @@ call_wifi_pass() {
   echo -e "${RESET}"
 }
 
+#Scan with Webcaom
 call_wifi_scan() {
   # Vars
   wifiqrdata=''
@@ -174,41 +192,77 @@ call_wifi_scan() {
 
   # Check if the QR contains WiFi data or not
   if echo $wifiqrdata | grep --quiet ^WIFI; then
+
     ## Go Go GUI and CLI Mod
     # ssid & key are not always in the same sequence - fix by using a dict and cut identifier for first key
     declare -A wifiqrcred
     wifiqrcred+=([$(echo $wifiqrdata | cut -b 6- | awk -F';' '{print $1}' | cut -d":" -f1)]=$(echo $wifiqrdata | cut -b 6- | awk -F';' '{print $1}' | cut -d":" -f2))
-    wifiqrcred+=([$(echo $wifiqrdata | awk -F';' '{print $2}' | cut -d":" -f1)]=$(echo $wifiqrdata | awk -F';' '{print $2}' | cut -d":" -f2))
-    wifiqrcred+=([$(echo $wifiqrdata | awk -F';' '{print $3}' | cut -d":" -f1)]=$(echo $wifiqrdata | awk -F';' '{print $3}' | cut -d":" -f2))
+    wifiqrcred+=([$(echo "$wifiqrdata" | awk -F';' '{print $2}' | cut -d":" -f1)]=$(echo "$wifiqrdata" | awk -F';' '{print $2}' | cut -d":" -f2))
+    wifiqrcred+=([$(echo "$wifiqrdata" | awk -F';' '{print $3}' | cut -d":" -f1)]=$(echo "$wifiqrdata" | awk -F';' '{print $3}' | cut -d":" -f2))
+    wifiqrcred+=([$(echo "$wifiqrdata" | awk -F';' '{print $4}' | cut -d":" -f1)]=$(echo "$wifiqrdata" | awk -F';' '{print $4}' | cut -d":" -f2))
+
     QSSID=${wifiqrcred[S]}
     QKEES=${wifiqrcred[P]}
-    QINFO=$(echo -e "SSID: $QSSID PASS: $QKEES")
-    #echo "$wifiqrdata"
-    #echo $QINFO
-    if nmcli device wifi list | grep -w "$QSSID"; then
+    QHIDE=${wifiqrcred[H]}
+    QTYPE=${wifiqrcred[T]}
+
+   if [[ "$QHIDE" == "true" ]]; then
+       echo -e "${GREEN}==================${RESET}"
+       echo -e "${BOLD}${WHITE}It's is HIDDEN ${RESET}"
+       echo -e "${GREEN}==================${RESET}"
+
+   elif nmcli device wifi list | grep -w "$QSSID"; then
       echo -e "${GREEN}==================${RESET}"
       echo -e "${BOLD}${WHITE}$QSSID is Online ${RESET}"
       echo -e "${GREEN}==================${RESET}"
       QSSIDO=ON
-    else
+
+   else
       echo -e "${RED}==================${RESET}"
       echo -e "${BOLD}${WHITE}cant see $QSSID ${RESET}"
       echo -e "${RED}==================${RESET}"
       QSSIDO=OFF
-    fi
+   fi 
+ 
 
   else
     echo -e "${RED}==================${RESET}"
     echo -e "${BOLD}${WHITE}Its not WiFi QR ${RESET}"
     echo -e "${RED}==================${RESET}"
-    echo -e "${BOLD}${BLUE}$wifiqrdata ${RESET}"
+    echo -e "${BOLD}${BLUE} $wifiqrdata ${RESET}"
     echo -e "${BLUE}==================${RESET}"
     QSSIDO=NOWIFI
   fi
 
+# key-mgmt type convert
+
+  if [[ -z "$QTYPE" ]] ; then
+         NTYPE="none"
+  elif [[ "$QTYPE" == "WEP" ]] ; then
+         NTYPE="ieee8021x"
+  elif [[ "$QTYPE" == "WPA" ]] ; then
+         NTYPE="wpa-psk"
+  else
+         echo "unknow or need to add key-mgmt type"
+  fi
+
+
   # Append scan results to file
   #echo $wifiqrdata >> $ScanResult
+}
 
+
+call_wifi_scan_terminal() {
+	call_wifi_scan
+
+	if [[ "$QHIDE" == "true" ]]; then
+		scan_connect_hidden
+	elif [[ "$QSSIDO" == "ON" ]]; then
+		scan_connect
+	else
+		echo "Can't find Network and Can't Connect"
+		exit 0
+	fi
 }
 
 call_wifi_scan_gui() {
@@ -222,8 +276,7 @@ call_wifi_scan_gui() {
       exit
     fi
   elif
-    [[ "$QSSIDO" =~ "OFF" ]]
-  then
+    [[ "$QSSIDO" =~ "OFF" ]]; then
     zenity --question --title="Can't find WiFi" --text="Can't find '$QSSID'.\nDo you want to retry the scan?" --width=200 --height=120 --icon-name=network-wireless-offline 2>/dev/null
     if [ $? = 0 ]; then
       nmcli radio wifi off
@@ -232,8 +285,16 @@ call_wifi_scan_gui() {
     else
       exit
     fi
-  fi
+  elif 
+    [[ "$QHIDE" =~ "true" ]]; then
+    zenity --question --title="Connect to Hidden WiFi" --text="Connect to '$QSSID'?" --width=200 --height=120 --icon-name=network-wireless 2>/dev/null
+       if [ $? = 0 ]; then
+      	  scan_connect_hidden
+    	else
+      	  exit
+       fi
 
+  fi
 }
 
 scan_connect() {
@@ -242,7 +303,14 @@ scan_connect() {
   nmcli dev wifi connect "$QSSID" password "$QKEES" >/dev/null 2>&1
 }
 
-
+scan_connect_hidden() {
+  nmcli radio wifi on
+  nmcli con delete "$QSSID" >/dev/null 2>&1
+  nmcli con add type wifi con-name "$QSSID" ssid "$QSSID" >/dev/null 2>&1
+  nmcli con modify "$QSSID" wifi-sec.key-mgmt "$NTYPE" >/dev/null 2>&1
+  nmcli con modify "$QSSID" wifi-sec.psk "$QKEES" >/dev/null 2>&1
+  nmcli con up "$QSSID" >/dev/null 2>&1
+}
 
 case $1 in
 
@@ -260,8 +328,7 @@ case $1 in
   ;;
 [Ss])
   echo "qr scan"
-  call_wifi_scan
-  scan_connect
+  call_wifi_scan_terminal
   ;;
 [Qq])
   echo "qr scan with gui"
@@ -279,5 +346,6 @@ case $1 in
 			q for QR Scan and Connect WiFi GUI
 			v for WiFi-QR Version is $VERSION
 		"
+		current_wifi_qr
   ;;
 esac
